---
title: "optimize.marsh.wren.rad"
author: "Devon DeRaad"
date: '2022-08-15'
output: html_document
---

# Optimize 'm'
```{r}
#load RADstackshelpR package
library(RADstackshelpR)
library(ggplot2)
#load gridExtra package to combine ggplot visualizations
library(gridExtra)
#if we have already read in the 16 vcf files and saved the details as an 'Rdata' file, load it in here:
load("~/Desktop/marsh.wren.rad/denovo.optimization.RData")
```

```{r, eval=FALSE}
#optimize_m function will generate summary stats on your 5 iterative runs
#input can be full path to each file, or just the file name if the vcf files are in your working directory
m.out<-optimize_m(m3="/Users/devder/Desktop/marsh.wren.rad/m3.vcf",
           m4="/Users/devder/Desktop/marsh.wren.rad/m4.vcf",
           m5="/Users/devder/Desktop/marsh.wren.rad/m5.vcf",
           m6="/Users/devder/Desktop/marsh.wren.rad/m6.vcf",
           m7="/Users/devder/Desktop/marsh.wren.rad/m7.vcf")
```

```{r}
#Assigning the output of this function to the variable 'm.out' should generate a list containing five objects of class 'data.frame' with the following characteristics: 'depth' showing depth per sample for each m value, 'snp' showing the number of non-missing SNPs retained in each sample at each m value, 'loci' showing the number of non-missing loci retained in each sample at each m value, 'snp.R80' showing the total number of SNPs retained at an 80% completeness cutoff, and 'loci.R80' showing the total number of polymorphic loci retained at an 80% completeness cutoff.

#Use this output list as input for this function, to visualize the effect of varying m on the depth of each sample
vis_depth(output = m.out)

#visualize the effect of varying m on the number of SNPs retained
vis_snps(output = m.out, stacks_param = "m")

#visualize the effect of varying m on the number of loci retained
vis_loci(output = m.out, stacks_param = "m")
```

# Optimize 'M'
```{r, eval=FALSE}
#optimize_bigM function will generate summary stats on your 8 iterative runs
M.out<-optimize_bigM(M1="/Users/devder/Desktop/marsh.wren.rad/bigM1.vcf",
           M2="/Users/devder/Desktop/marsh.wren.rad/bigM2.vcf",
           M3="/Users/devder/Desktop/marsh.wren.rad/bigM3.vcf",
           M4="/Users/devder/Desktop/marsh.wren.rad/bigM4.vcf",
           M5="/Users/devder/Desktop/marsh.wren.rad/bigM5.vcf",
           M6="/Users/devder/Desktop/marsh.wren.rad/bigM6.vcf",
           M7="/Users/devder/Desktop/marsh.wren.rad/bigM7.vcf",
           M8="/Users/devder/Desktop/marsh.wren.rad/bigM8.vcf")
```

```{r}
#Assigning the output of this function to the variable 'M.out' should generate a list containing four objects of class 'data.frame' with the following characteristics: 'snp' showing the number of non-missing SNPs retained in each sample at each m value, 'loci' showing the number of non-missing loci retained in each sample at each m value, 'snp.R80' showing the total number of SNPs retained at an 80% completeness cutoff, and 'loci.R80' showing the total number of polymorphic loci retained at an 80% completeness cutoff.

#use this function to visualize the effect of varying 'M' on the number of SNPs retained
vis_snps(output = M.out, stacks_param = "M")

#visualize the effect of varying 'M' on the number of polymorphic loci retained
vis_loci(output = M.out, stacks_param = "M")
```


# Optimize 'n'
```{r, eval=FALSE}
#optimize n
n.out<-optimize_n(nequalsMminus1="/Users/devder/Desktop/marsh.wren.rad/n3.vcf",
           nequalsM="/Users/devder/Desktop/marsh.wren.rad/n4.vcf",
           nequalsMplus1="/Users/devder/Desktop/marsh.wren.rad/n5.vcf")
#save the details to an 'Rdata' file so that this script can be rerun without having to load in all 16 vcf files next time
#save(m.out, M.out, n.out, file = "~/Desktop/marsh.wren.rad/denovo.optimization.RData")
```

```{r}
##Assigning the output of this function to the variable 'n.out' should generate a single object of class 'data.frame' showing the number of SNPs and loci retained across filtering levels for each value of n.

#visualize the effect of varying n on the number of SNPs retained
vis_snps(output = n.out, stacks_param = "n")
#visualize the effect of varying n on the number of polymorphic loci retained
vis_loci(output = n.out, stacks_param = "n")
```

# plot summary figure
```{r}
#combine all of these prior visulizations in a single list
gl<-list()
gl[[1]]<-vis_depth(output = m.out)
gl[[2]]<-vis_snps(output = m.out, stacks_param = "m")
gl[[3]]<-vis_loci(output = m.out, stacks_param = "m")
gl[[4]]<-vis_snps(output = M.out, stacks_param = "M")
gl[[5]]<-vis_loci(output = M.out, stacks_param = "M")
gl[[6]]<-vis_snps(output = n.out, stacks_param = "n")
gl[[7]]<-vis_loci(output = n.out, stacks_param = "n")

#visualize each item of the list as part of a single grid
grid.arrange(grobs = gl, widths = c(1,1,1,1,1,1),
  layout_matrix = rbind(c(1,1,2,2,3,3),
                        c(4,4,4,5,5,5),
                        c(6,6,6,7,7,7)))

#save plot
g<-arrangeGrob(grobs = gl, widths = c(1,1,1,1,1,1),
  layout_matrix = rbind(c(1,1,2,2,3,3),
                        c(4,4,4,5,5,5),
                        c(6,6,6,7,7,7)))

ggsave(file="~/Desktop/marsh.wren.rad/denovo.optimization.png", g, width = 10, height=8, units = "in")
```

