---
title: "run admixture iterations"
author: "Devon DeRaad"
date: '2022-10-03'
output: html_document
---


```{r}
#load packages
library(vcfR)
library(SNPfiltR)
library(RColorBrewer)
library(ggplot2)
library(StAMPP)
library(adegenet)

#read in vcf as vcfR
vcfR <- read.vcfR("~/Desktop/marsh.wren.rad/unlinked.filtered.vcf.gz")

samps<-read.csv("~/Desktop/marsh.wren.rad/marsh.wren.rad.sampling.csv")
#retain samples that were sequenced successfully
samps<-samps[samps$Tissue.num %in% colnames(vcfR@gt),]
#reorder sampling file to match order of samples in vcf
samps<-samps[match(colnames(vcfR@gt)[-1], samps$Tissue.num),]
samps$Tissue.num == colnames(vcfR@gt)[-1] #check that order matches

table(samps$Population)

#must make chromosome names non-numeric for plink
vcfR@fix[,1]<-paste("a", vcfR@fix[,1], sep="")
#write this version to disk
vcfR::write.vcf(vcfR, file="~/Desktop/marsh.wren.rad/admix.vcf.gz")
```

### use this thinned file to execute ADMIXTURE on the cluster using this script:
```{bash, eval=FALSE}
#!/bin/sh
#
#SBATCH --job-name=admixture               # Job Name
#SBATCH --nodes=1             # 40 nodes
#SBATCH --ntasks-per-node=5              # 40 CPU allocation per Task
#SBATCH --partition=sixhour         # Name of the Slurm partition used
#SBATCH --chdir=/home/d669d153/work/marsh.wren.rad/admixture    # Set working d$
#SBATCH --mem-per-cpu=1gb            # memory requested
#SBATCH --time=360

#use plink to convert vcf directly to bed format:
/home/d669d153/work/plink --vcf unlinked.filtered.vcf --double-id --allow-extra-chr --make-bed --out binary_fileset
#fix chromosome names
cut -f2- binary_fileset.bim  > temp
awk 'BEGIN{FS=OFS="\t"}{print value 1 OFS $0}' temp > binary_fileset.bim

#run admixture for a K of 1-5, using cross-validation, with 10 threads
for K in 1 2 3 4 5; 
do /home/d669d153/work/admixture_linux-1.3.0/admixture --cv -j10 binary_fileset.bed $K | tee log${K}.out;
done

#Which K iteration is optimal according to ADMIXTURE ?
grep -h CV log*.out > log.errors.txt
```

```{r}
#read in ADMIXTURE results
#setwd to admixture directory run on the cluster
setwd("~/Desktop/marsh.wren.rad/admixture")

#read in log error values to determine optimal K
log<-read.table("log.errors.txt")[,c(3:4)]
#use double backslash to interpret the opening parentheses literally in the regular expression
log$V3<-gsub("\\(K=", "", log$V3)
log$V3<-gsub("):", "", log$V3)
#interpret K values as numerical
log$V3<-as.numeric(log$V3)
#rename columns
colnames(log)<-c("Kvalue","cross.validation.error")

#make plot showing the cross validation error across K values 1:5
ggplot(data=log, aes(x=Kvalue, y=cross.validation.error, group=1)) +
  geom_line(linetype = "dashed")+
  geom_point()+
  ylab("cross-validation error")+
  xlab("K")+
  scale_x_continuous(breaks = c(1:5))+
  theme_classic()
```

```{r}
setwd("~/Desktop/marsh.wren.rad/admixture")
#read in input file in order to get list of input samples in order
sampling<-read.table("binary_fileset.fam")[,1]
sampling
#read in all ten runs and save each dataframe in a list
runs<-list()
#read in log files
for (i in 1:5){
  runs[[i]]<-read.table(paste0("binary_fileset.", i, ".Q"))
}

#plot each run
for (i in 1:5){
barplot(t(as.matrix(runs[[i]])), col=rainbow(i), ylab="Ancestry", border="black")
}
```

### reorder barplot by q value
```{r}
#check that order matches
sampling == samps$Tissue.num
#save q value
samps$western.qvalue<-runs[[2]][,2]
#write to disk
#write.csv(x = samps, file="~/Desktop/marsh.wren.rad/samples.with.qvalues.csv")
#reorder dataframe
runs[[2]]<-runs[[2]][order(runs[[2]]$V1),]
#replot
barplot(t(as.matrix(runs[[2]])), col=c("#8C510A","#01665E"), ylab="Ancestry", border="black")
## Open a pdf file
#pdf("~/Desktop/marsh.wren.rad/admixture.pdf", width=8.5, height=4)
##replot
#barplot(t(as.matrix(runs[[2]])), col=c("#8C510A","#01665E"), ylab="Ancestry proportion", #border="black")
##close
#dev.off()
```

### assess the mean ancestry of "pure parental individuals" for each lineage (i.e., greater than 85% assignment to one of the two ancestry bins)
```{r}
#get eastern qvalue
eastern.qvalue<-1-samps$western.qvalue

#set breakpoints
ax<-seq(.85,1, by= .015)

#plot overlaid histograms colored by parental pop
plot(hist(eastern.qvalue[eastern.qvalue > .85], breaks=ax, plot=FALSE), col=alpha("#8C510A", .5))
plot(hist(samps$western.qvalue[samps$western.qvalue > .85], breaks=ax, plot=FALSE), col=alpha("#01665E", .5), add=TRUE)
abline(v=mean(eastern.qvalue[eastern.qvalue > .85]), col=alpha("#8C510A"), lwd=3, lty=2)
abline(v=mean(samps$western.qvalue[samps$western.qvalue > .85]), col=alpha("#01665E"), lwd=3, lty=2)

#perform T-test with null hypothesis of equal means
t.test(x = samps$western.qvalue[samps$western.qvalue > .85],y = eastern.qvalue[eastern.qvalue > .85])

# Open a pdf file
#pdf("~/Desktop/marsh.wren.rad/admixture.tail.histograms.pdf", width=8.5, height=4)
##replot
#plot(hist(eastern.qvalue[eastern.qvalue > .85], breaks=ax, plot=FALSE), col=alpha("#8C510A", .5))
#plot(hist(samps$western.qvalue[samps$western.qvalue > .85], breaks=ax, plot=FALSE), col=alpha("#01665E", .5), #add=TRUE)
#abline(v=mean(eastern.qvalue[eastern.qvalue > .85]), col=alpha("#8C510A"), lwd=3, lty=2)
#abline(v=mean(samps$western.qvalue[samps$western.qvalue > .85]), col=alpha("#01665E"), lwd=3, lty=2)
##close
#dev.off()
```

